workspace:

  base: /go/src/github.com/glynternet
  path: packing


pipeline:
  generate-proto-go:
    image: grpc/go:1.0
    commands:
      - go generate -v ./...

  run-unit-tests:
    image: golang:1.10.4
    commands:
      - go test -v -race ./...

  run-linters:
    image: glynhanmer/go-linters:1.10.3-alpine3.7-v0.2.0
    environment:
      - CONCURRENCY=1
