# dubplate version: v1.0.0-2-g61f3327 (manually edited)

workspace:

  base: /go/src/github.com/glynternet
  path: packing

pipeline:
  generate-proto-go:
    image: grpc/go:1.0
    commands:
      - go generate -v ./...

  run-unit-tests:
    image: golang:1.10.4
    commands:
      - go test -v -race ./...

  # drone mounts the root directory of the repository to the container and sets
  # it as the working directory
  run-linters:
    image: glynhanmer/go-linters:1.10.3-alpine3.7-v0.2.0
    environment:
      - CONCURRENCY=1

  build-binaries:
    image: golang:1.10.4
    commands:
      - make binaries
