# dubplate version: v0.9.0 (manually edited)

workspace:

  base: /go/src
  path: github.com/glynternet/packing


pipeline:
  generate-proto-go:
    image: golang:1.15.4
    commands:
      - apt update
      - apt install -y protobuf-compiler
      - go get -u github.com/golang/protobuf/proto
      - go get -u github.com/golang/protobuf/protoc-gen-go
      - go get -u google.golang.org/grpc/cmd/protoc-gen-go-grpc
      - go get -u google.golang.org/grpc
      - go generate -v ./...

  run-unit-tests:
    image: golang:1.15.4
    commands:
      - go test -v -race ./...

  # drone mounts the root directory of the repository to the container and sets
  # it as the working directory
  run-linters:
    image: golangci/golangci-lint:v1.32.2-alpine
    commands:
      - golangci-lint run -v

  build-binaries:
    image: golang:1.15.4
    commands:
      - make binaries

  # images are not yet supported
  # build-images:
    # image: HMMMMMMMMM
    # environment:
      # - DOCKER_USERNAME=
